import {notFound} from 'next/navigation';
import {ArrowUpRight} from 'lucide-react';
import {isLocale,locales} from '@/lib/i18n';
import {business} from '@/lib/business';
import {products} from '@/lib/products';
import {catalogText} from '@/lib/catalog-i18n';
import {pageMetadata} from '@/lib/seo';
import {QuoteForm} from '@/components/quote-form';
export function generateStaticParams(){return locales.map(locale=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}) {const {locale}=await params;return isLocale(locale)?pageMetadata(locale,'/quote',catalogText[locale].quote,catalogText[locale].handoff):{};}
export default async function QuotePage({params}:{params:Promise<{locale:string}>}) {const {locale}=await params;if(!isLocale(locale))notFound();const copy={ar:{kicker:'استفسار مشروع',title:'التصاميم المختارة.\nطلب عرض واضح.',body:'أضف الموديلات والكميات التقريبية، ثم راجع الرسالة قبل إرسالها عبر واتساب.',emailAction:'مراسلتنا عبر البريد',emailAria:'مراسلة قسم المبيعات عبر البريد الإلكتروني',emailSubject:'طلب عرض سعر - BIN MANSOOR CARPET'},en:{kicker:'Project enquiry',title:'Selected designs.\nA considered quotation.',body:'Add your preferred models and estimated quantities, then review the message before sending it through WhatsApp.',emailAction:'Email Sales',emailAria:'Email the sales team',emailSubject:'Request for Quotation - BIN MANSOOR CARPET'},tr:{kicker:'Proje talebi',title:'Seçili tasarımlar.\nNet bir teklif talebi.',body:'Modelleri ve tahmini miktarları ekleyin, ardından WhatsApp üzerinden göndermeden önce mesajı inceleyin.',emailAction:'Satış Ekibine E-posta Gönder',emailAria:'Satış ekibine e-posta gönder',emailSubject:'Fiyat Teklifi Talebi - BIN MANSOOR CARPET'}}[locale];const emailHref=business.officialEmail?`mailto:${business.officialEmail}?subject=${encodeURIComponent(copy.emailSubject)}`:null;return <main id="main-content" className="quote-page"><section className="quote-hero site-shell"><div><p className="eyebrow">{copy.kicker}</p><h1 className="whitespace-pre-line">{copy.title}</h1></div><div><p>{copy.body}</p>{emailHref&&<a href={emailHref} className="btn-text mt-6" aria-label={copy.emailAria}>{copy.emailAction}<ArrowUpRight className="size-4" aria-hidden="true"/></a>}</div></section><section className="quote-workspace site-shell"><QuoteForm locale={locale} products={products}/></section></main>;}
