import {business} from '@/lib/business';
import type {Locale,LocalizedText} from '@/lib/products';

export function FutureSections({locale}:{locale:Locale}) {
 const labels={ar:{factory:'داخل المصنع',applications:'مجالات الاستخدام',projects:'المشاريع',clients:'العملاء',details:'التصنيع والخدمات',email:'البريد الرسمي',catalog:'الكتالوج',social:'القنوات الرسمية'},en:{factory:'Inside the factory',applications:'Applications',projects:'Projects',clients:'Clients',details:'Manufacturing & services',email:'Official email',catalog:'Catalogue',social:'Official channels'},tr:{factory:'Fabrikadan',applications:'Kullanım alanları',projects:'Projeler',clients:'Müşteriler',details:'Üretim ve hizmetler',email:'Resmî e-posta',catalog:'Katalog',social:'Resmî kanallar'}}[locale];
 const details=[business.machineDetails,business.materials,business.certifications,business.exportMarkets,business.shippingMethods,business.leadTime,business.customManufacturing,business.customDesign,business.customColors].filter((value):value is LocalizedText=>Boolean(value?.[locale]));
 const numericLabels={factoryArea:{ar:'مساحة المصنع (م²)',en:'Factory area (m²)',tr:'Fabrika alanı (m²)'},employeeCount:{ar:'الموظفون',en:'Employees',tr:'Çalışanlar'},dailyCapacity:{ar:'الطاقة اليومية (م²)',en:'Daily capacity (m²)',tr:'Günlük kapasite (m²)'},monthlyCapacity:{ar:'الطاقة الشهرية (م²)',en:'Monthly capacity (m²)',tr:'Aylık kapasite (m²)'},annualCapacity:{ar:'الطاقة السنوية (م²)',en:'Annual capacity (m²)',tr:'Yıllık kapasite (m²)'}};
 const numericFacts=(Object.keys(numericLabels) as (keyof typeof numericLabels)[]).filter(key=>business[key]!==null);
 const resources=[business.officialEmail&&{label:labels.email,href:`mailto:${business.officialEmail}`},business.catalogPdf&&{label:labels.catalog,href:business.catalogPdf},...Object.entries(business.socialLinks??{}).map(([name,href])=>({label:`${labels.social}: ${name}`,href}))].filter((item):item is {label:string;href:string}=>Boolean(item));
 return <>
  {(business.factoryPhotos?.length||business.factoryVideo)?<section className="site-shell py-16"><h2 className="text-3xl">{labels.factory}</h2><div className="mt-8 grid gap-6 md:grid-cols-2">{business.factoryPhotos?.map(photo=><img key={photo.src} src={photo.src} alt={photo.alt[locale]} loading="lazy"/>)}{business.factoryVideo&&<video controls preload="none" src={business.factoryVideo.src} poster={business.factoryVideo.poster}><track kind="captions" src={business.factoryVideo.captions} srcLang={locale}/></video>}</div></section>:null}
  {(details.length>0||numericFacts.length>0||resources.length>0)&&<section className="site-shell py-16"><h2 className="text-3xl">{labels.details}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{details.map(value=><p key={value.en}>{value[locale]}</p>)}{numericFacts.map(key=><p key={key}>{numericLabels[key][locale]}: {business[key]}</p>)}{resources.map(item=><a className="underline" key={item.href} href={item.href}>{item.label}</a>)}</div></section>}
  {(['applications','projects','clients'] as const).map(key=>business[key]?.length?<section key={key} className="site-shell py-16"><h2 className="text-3xl">{labels[key]}</h2><ul className="mt-8 grid gap-6 md:grid-cols-3">{business[key]?.map((value,index)=><li key={index}>{value[locale]}</li>)}</ul></section>:null)}
 </>;
}
