import {business} from '@/lib/business';
import type {Locale} from '@/lib/products';
export function FutureSections({locale}:{locale:Locale}) {
 const labels={ar:{factory:'داخل المصنع',applications:'مجالات الاستخدام',projects:'المشاريع',clients:'العملاء',details:'التصنيع والخدمات'},en:{factory:'Inside the factory',applications:'Applications',projects:'Projects',clients:'Clients',details:'Manufacturing & services'},tr:{factory:'Fabrikadan',applications:'Kullanım alanları',projects:'Projeler',clients:'Müşteriler',details:'Üretim ve hizmetler'}}[locale];
 const details=[business.machineDetails,business.materials,business.certifications,business.exportMarkets,business.shipping,business.leadTime,business.customManufacturing,business.customDesign].filter(v=>v&&v[locale]);
 const numericLabels={factoryArea:{ar:'مساحة المصنع (م²)',en:'Factory area (m²)',tr:'Fabrika alanı (m²)'},employees:{ar:'الموظفون',en:'Employees',tr:'Çalışanlar'},monthlyCapacity:{ar:'الطاقة الشهرية (م²)',en:'Monthly capacity (m²)',tr:'Aylık kapasite (m²)'},annualCapacity:{ar:'الطاقة السنوية (م²)',en:'Annual capacity (m²)',tr:'Yıllık kapasite (m²)'}};
 const numericFacts=(Object.keys(numericLabels) as (keyof typeof numericLabels)[]).filter(k=>business[k]!==null);
 if(numericFacts.length)details.push({ar:numericFacts.map(k=>`${numericLabels[k].ar}: ${business[k]}`).join(' / '),en:numericFacts.map(k=>`${numericLabels[k].en}: ${business[k]}`).join(' / '),tr:numericFacts.map(k=>`${numericLabels[k].tr}: ${business[k]}`).join(' / ')});
 return <>{(business.factoryPhotos?.length||business.factoryVideo)?<section className="site-shell py-16"><h2 className="text-3xl">{labels.factory}</h2><div className="mt-8 grid gap-6 md:grid-cols-2">{business.factoryPhotos?.map(p=><img key={p.src} src={p.src} alt={p.alt[locale]} loading="lazy"/>)}{business.factoryVideo&&<video controls preload="none" src={business.factoryVideo}/>}</div></section>:null}{details.length>0&&<section className="site-shell py-16"><h2>{labels.details}</h2>{details.map((v,i)=><p key={i}>{v?.[locale]}</p>)}</section>}{(['applications','projects','clients'] as const).map(key=>business[key]?.length?<section key={key} className="site-shell py-16"><h2 className="text-3xl">{labels[key]}</h2><ul className="mt-8 grid gap-6 md:grid-cols-3">{business[key]?.map((v,i)=><li key={i}>{v[locale]}</li>)}</ul></section>:null)}</>;
}
