'use client';

import {useEffect,useMemo,useState} from 'react';
import {Copy,Download,ExternalLink,FileUp,LogOut,Mail,Plus,Save,Search,Upload} from 'lucide-react';
import {OUTREACH_COUNTRIES,OUTREACH_EMAIL_TYPES,OUTREACH_LANGUAGES,OUTREACH_SECTORS,OUTREACH_SOURCES,OUTREACH_STATUSES,SAUDI_CITIES,copyableEmail,createLead,defaultIncludeMoq,effectiveLeadStatus,exportLeadCsv,generateOutreachEmail,gmailComposeUrl,markLeadSent,parseLeadCsv,suggestedFollowUpType,validateBackup} from '@/lib/outreach';
import type {EmailDraft,Lead,OutreachDesign,OutreachEmailType,OutreachStatus} from '@/lib/outreach';
import {loadLeads,removeLead,replaceLeads,saveLead,saveLeads} from '@/lib/outreach-store';

function downloadFile(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
function dateTime(value:string){return value?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
function localDate(value:string){return value?value.slice(0,10):'';}

export function OutreachDashboard({designs}:{designs:OutreachDesign[]}){
 const [leads,setLeads]=useState<Lead[]>([]);const [selectedId,setSelectedId]=useState('');const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [importErrors,setImportErrors]=useState<string[]>([]);
 const [search,setSearch]=useState('');const [country,setCountry]=useState('');const [city,setCity]=useState('');const [sector,setSector]=useState('');const [status,setStatus]=useState('');const [language,setLanguage]=useState('');
 const [newCompany,setNewCompany]=useState('');const [newEmail,setNewEmail]=useState('');
 const [emailType,setEmailType]=useState<OutreachEmailType>('FIRST CONTACT');const [opening,setOpening]=useState('');const [includeMoq,setIncludeMoq]=useState(false);const [includeOptOut,setIncludeOptOut]=useState(true);const [selectedDesigns,setSelectedDesigns]=useState<string[]>([]);const [designSearch,setDesignSearch]=useState('');const [draft,setDraft]=useState<EmailDraft|null>(null);

 useEffect(()=>{loadLeads().then(items=>{const sorted=items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));setLeads(sorted);setSelectedId(sorted[0]?.id??'');setIncludeMoq(sorted[0]?defaultIncludeMoq(sorted[0].sector):false);setReady(true);}).catch(()=>{setNotice('The local lead database could not be opened.');setReady(true);});},[]);
 const selected=leads.find(lead=>lead.id===selectedId)??null;

 function selectLead(lead:Lead|null){setSelectedId(lead?.id??'');setEmailType('FIRST CONTACT');setIncludeMoq(lead?defaultIncludeMoq(lead.sector):false);setIncludeOptOut(true);setOpening('');setSelectedDesigns([]);setDraft(null);}

 const summary=useMemo(()=>({total:leads.length,new:leads.filter(item=>item.status==='NEW').length,contacted:leads.filter(item=>item.status==='CONTACTED').length,due:leads.filter(item=>effectiveLeadStatus(item)==='FOLLOW-UP DUE').length,replied:leads.filter(item=>item.status==='REPLIED').length,quote:leads.filter(item=>item.status==='QUOTE REQUESTED').length}),[leads]);
 const countries=[...new Set([...OUTREACH_COUNTRIES,...leads.map(item=>item.country).filter(Boolean)])];const cities=[...new Set([...SAUDI_CITIES,...leads.map(item=>item.city).filter(Boolean)])];
 const filtered=useMemo(()=>leads.filter(lead=>{const needle=search.trim().toLowerCase();return (!needle||[lead.companyName,lead.contactName,lead.email].some(value=>value.toLowerCase().includes(needle)))&&(!country||lead.country===country)&&(!city||lead.city===city)&&(!sector||lead.sector===sector)&&(!status||effectiveLeadStatus(lead)===status)&&(!language||lead.language===language);}),[leads,search,country,city,sector,status,language]);
 const productOptions=useMemo(()=>designs.filter(item=>!designSearch.trim()||[item.code,item.name.en,item.name.ar,item.line].join(' ').toLowerCase().includes(designSearch.trim().toLowerCase())),[designSearch,designs]);

 function replaceState(updated:Lead){setLeads(items=>items.map(item=>item.id===updated.id?updated:item));setNotice('Saved locally in this browser.');void saveLead(updated).catch(()=>setNotice('Unable to save the lead locally.'));}
 function patchLead(patch:Partial<Lead>){if(!selected)return;replaceState({...selected,...patch,updatedAt:new Date().toISOString()});setDraft(null);}
 function addLead(){if(!newCompany.trim()||!/^\S+@\S+\.\S+$/.test(newEmail.trim())){setNotice('Enter a company and valid email.');return;}if(leads.some(item=>item.email.toLowerCase()===newEmail.trim().toLowerCase())){setNotice('A lead with this email already exists.');return;}const lead=createLead({companyName:newCompany,email:newEmail});setLeads(items=>[lead,...items]);selectLead(lead);setNewCompany('');setNewEmail('');void saveLead(lead);setNotice('New lead added locally.');}
 async function importCsv(file:File){const result=parseLeadCsv(await file.text());const existing=new Set(leads.map(item=>item.email.toLowerCase()));const duplicates=result.leads.filter(item=>existing.has(item.email));const accepted=result.leads.filter(item=>!existing.has(item.email));const errors=[...result.errors.map(error=>`Row ${error.row}: ${error.message}`),...duplicates.map(item=>`Skipped existing email: ${item.email}`)];if(accepted.length){await saveLeads(accepted);setLeads(items=>[...accepted,...items]);selectLead(accepted[0]);}setImportErrors(errors);setNotice(`${accepted.length} lead${accepted.length===1?'':'s'} imported; ${errors.length} row${errors.length===1?'':'s'} need review.`);}
 async function importBackup(file:File){try{const restored=validateBackup(JSON.parse(await file.text()));await replaceLeads(restored);setLeads(restored);selectLead(restored[0]??null);setNotice(`${restored.length} leads restored from backup.`);setImportErrors([]);}catch(error){setNotice(error instanceof Error?error.message:'Invalid backup file.');}}
 function generate(type=emailType){if(!selected)return;try{const chosen=selectedDesigns.map(key=>designs.find(item=>item.key===key)).filter((item):item is OutreachDesign=>Boolean(item));setEmailType(type);setDraft(generateOutreachEmail({lead:selected,type,personalOpeningLine:opening,includeMoq,includeOptOut,designs:chosen}));setNotice('Draft prepared for review. Nothing has been sent.');}catch(error){setNotice(error instanceof Error?error.message:'Unable to prepare the draft.');}}
 async function markSent(){if(!selected||!draft)return;const updated=markLeadSent(selected,draft);replaceState(updated);setDraft(null);setNotice('Marked as sent. Suggested follow-up: '+(updated.nextFollowUpAt||'none after Follow-Up #2')+'.');}
 async function deleteSelected(){if(!selected||!confirm(`Remove ${selected.companyName} from this browser?`))return;await removeLead(selected.id);const remaining=leads.filter(item=>item.id!==selected.id);setLeads(remaining);selectLead(remaining[0]??null);setNotice('Lead removed from this browser.');}

 return <main className="outreach-app">
  <header className="outreach-header"><div><p className="outreach-kicker">PRIVATE · BIN MANSOOR CARPET</p><h1>Sales Outreach Assistant</h1><p>Local lead workspace · every email requires manual review and sending.</p></div><form method="post" action="/admin/outreach/logout"><button className="outreach-quiet" type="submit"><LogOut/>Sign out</button></form></header>
  <section className="outreach-summary" aria-label="Lead summary">{[['Total Leads',summary.total],['New',summary.new],['Contacted',summary.contacted],['Follow-Up Due',summary.due],['Replied',summary.replied],['Quote Requested',summary.quote]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
  <section className="outreach-tools"><div className="outreach-quick-add"><input aria-label="Company name" placeholder="Company name" value={newCompany} onChange={event=>setNewCompany(event.target.value)}/><input aria-label="Email" type="email" placeholder="contact@company.com" value={newEmail} onChange={event=>setNewEmail(event.target.value)}/><button type="button" onClick={addLead}><Plus/>New lead</button></div><div className="outreach-file-actions"><label><FileUp/>Import CSV<input type="file" accept=".csv,text/csv" onChange={event=>{const file=event.target.files?.[0];if(file)void importCsv(file);event.currentTarget.value='';}}/></label><button type="button" onClick={()=>downloadFile('bin-mansoor-leads.csv',exportLeadCsv(leads),'text/csv;charset=utf-8')}><Download/>Export CSV</button><button type="button" onClick={()=>downloadFile('bin-mansoor-outreach-backup.json',JSON.stringify({version:1,exportedAt:new Date().toISOString(),leads},null,2),'application/json')}><Download/>Export Backup</button><label><Upload/>Import Backup<input type="file" accept=".json,application/json" onChange={event=>{const file=event.target.files?.[0];if(file)void importBackup(file);event.currentTarget.value='';}}/></label></div></section>
  {notice&&<output className="outreach-notice">{notice}</output>}{importErrors.length>0&&<details className="outreach-errors"><summary>{importErrors.length} import item(s) need review</summary><ul>{importErrors.map((error,index)=><li key={`${error}-${index}`} >{error}</li>)}</ul></details>}
  <section className="outreach-filters"><label className="outreach-search"><Search/><input placeholder="Search company, contact or email" value={search} onChange={event=>setSearch(event.target.value)}/></label>{[[country,setCountry,'Country',countries],[city,setCity,'City',cities],[sector,setSector,'Sector',OUTREACH_SECTORS],[status,setStatus,'Status',OUTREACH_STATUSES],[language,setLanguage,'Language',OUTREACH_LANGUAGES]].map(([value,setter,label,options])=><label key={label as string}><span>{label as string}</span><select value={value as string} onChange={event=>(setter as (value:string)=>void)(event.target.value)}><option value="">All</option>{(options as readonly string[]).map(option=><option key={option}>{option}</option>)}</select></label>)}</section>
  <div className="outreach-workspace">
   <aside className="outreach-leads" aria-label="Leads"><div className="outreach-list-heading"><strong>{filtered.length} leads</strong><span>Stored on this device</span></div>{!ready?<p>Loading local workspace…</p>:filtered.length===0?<div className="outreach-empty"><p>No leads match this view.</p><small>Import a CSV or add a lead above. Production starts empty.</small></div>:filtered.map(lead=><button key={lead.id} type="button" className={lead.id===selectedId?'is-active':''} onClick={()=>selectLead(lead)}><span><strong>{lead.companyName}</strong><small>{lead.contactName||lead.email}</small></span><bdi>{effectiveLeadStatus(lead)}</bdi></button>)}</aside>
   <section className="outreach-detail">{!selected?<div className="outreach-empty"><Mail/><h2>Select a lead</h2><p>Review details and prepare one email at a time.</p></div>:<>
    <div className="outreach-detail-head"><div><p className="outreach-kicker">LEAD DETAIL</p><h2>{selected.companyName}</h2><a href={`mailto:${selected.email}`}>{selected.email}</a></div><div><button type="button" className="outreach-quiet" onClick={()=>generate('FIRST CONTACT')} disabled={selected.status==='DO NOT CONTACT'}>Generate Email</button><button type="button" className="outreach-quiet" onClick={()=>generate(suggestedFollowUpType(selected))} disabled={selected.status==='DO NOT CONTACT'}>Prepare Follow-Up</button></div></div>
    {selected.status==='DO NOT CONTACT'&&<p className="outreach-blocked" role="alert">Outreach is blocked. Change the status manually before preparing another email.</p>}
    <div className="outreach-fields"><label>Company<input value={selected.companyName} onChange={event=>patchLead({companyName:event.target.value})}/></label><label>Contact<input value={selected.contactName} onChange={event=>patchLead({contactName:event.target.value})}/></label><label>Title<input value={selected.jobTitle} onChange={event=>patchLead({jobTitle:event.target.value})}/></label><label>Email<input type="email" value={selected.email} onChange={event=>patchLead({email:event.target.value})}/></label><label>Phone<input value={selected.phone} onChange={event=>patchLead({phone:event.target.value})}/></label><label>Country<input list="outreach-countries" value={selected.country} onChange={event=>patchLead({country:event.target.value})}/><datalist id="outreach-countries">{OUTREACH_COUNTRIES.map(item=><option key={item}>{item}</option>)}</datalist></label><label>City<input list="outreach-cities" value={selected.city} onChange={event=>patchLead({city:event.target.value})}/><datalist id="outreach-cities">{SAUDI_CITIES.map(item=><option key={item}>{item}</option>)}</datalist></label><label>Sector<select value={selected.sector} onChange={event=>{const next=event.target.value as Lead['sector'];patchLead({sector:next});setIncludeMoq(defaultIncludeMoq(next));}}>{OUTREACH_SECTORS.map(item=><option key={item}>{item}</option>)}</select></label><label>Website<input type="url" value={selected.website} onChange={event=>patchLead({website:event.target.value})}/></label><label>Source<select value={selected.source} onChange={event=>patchLead({source:event.target.value as Lead['source']})}>{OUTREACH_SOURCES.map(item=><option key={item}>{item}</option>)}</select></label><label>Language<select value={selected.language} onChange={event=>patchLead({language:event.target.value as Lead['language']})}>{OUTREACH_LANGUAGES.map(item=><option key={item} value={item}>{item==='en'?'English':'Arabic'}</option>)}</select></label><label>Status<select value={selected.status} onChange={event=>patchLead({status:event.target.value as OutreachStatus})}>{OUTREACH_STATUSES.map(item=><option key={item}>{item}</option>)}</select></label><label>Last contacted<input readOnly value={dateTime(selected.lastContactedAt)}/></label><label>Next follow-up<input type="date" value={localDate(selected.nextFollowUpAt)} onChange={event=>patchLead({nextFollowUpAt:event.target.value})}/></label><label className="outreach-wide">Notes<textarea rows={4} value={selected.notes} onChange={event=>patchLead({notes:event.target.value})}/></label></div>
    <div className="outreach-detail-actions"><button type="button" onClick={()=>replaceState({...selected,updatedAt:new Date().toISOString()})}><Save/>Save</button><button type="button" className="outreach-danger" onClick={()=>void deleteSelected()}>Remove lead</button></div>
    <section className="outreach-history"><h3>Contact history</h3>{selected.history.length?<ol>{[...selected.history].reverse().map(entry=><li key={entry.id}><span>{entry.type}</span><strong>{entry.subject}</strong><time>{dateTime(entry.at)}</time></li>)}</ol>:<p>No sent activity recorded.</p>}</section>
    <section className="outreach-composer"><div className="outreach-composer-head"><div><p className="outreach-kicker">HUMAN REVIEW REQUIRED</p><h3>Email draft</h3></div><span>Nothing is sent automatically.</span></div><div className="outreach-compose-options"><label>Email type<select value={emailType} onChange={event=>{setEmailType(event.target.value as OutreachEmailType);setDraft(null);}}>{OUTREACH_EMAIL_TYPES.map(item=><option key={item}>{item}</option>)}</select></label><label className="outreach-wide">Personal Opening Line<input placeholder="I came across your hospitality projects in Riyadh…" value={opening} onChange={event=>setOpening(event.target.value)}/></label><label className="outreach-check"><input type="checkbox" checked={includeMoq} onChange={event=>setIncludeMoq(event.target.checked)}/>Include MOQ</label><label className="outreach-check"><input type="checkbox" checked={includeOptOut} onChange={event=>setIncludeOptOut(event.target.checked)}/>Include discreet opt-out</label></div>
     <details className="outreach-designs"><summary>Selected product links ({selectedDesigns.length}/3)</summary><label className="outreach-search"><Search/><input placeholder="Search BMC or WTW design" value={designSearch} onChange={event=>setDesignSearch(event.target.value)}/></label><div>{productOptions.map(item=><label key={item.key}><input type="checkbox" checked={selectedDesigns.includes(item.key)} disabled={!selectedDesigns.includes(item.key)&&selectedDesigns.length>=3} onChange={event=>setSelectedDesigns(keys=>event.target.checked?[...keys,item.key]:keys.filter(key=>key!==item.key))}/><span><strong>{item.code}</strong>{item.name[selected.language]} · {item.line}</span></label>)}</div></details>
     <button type="button" onClick={()=>generate()} disabled={selected.status==='DO NOT CONTACT'}>Generate / Refresh Draft</button>
     {draft&&<div className="outreach-preview"><label>TO<input readOnly value={draft.to}/></label><label>SUBJECT<input value={draft.subject} onChange={event=>setDraft({...draft,subject:event.target.value})}/></label><label>BODY<textarea rows={16} value={draft.body} onChange={event=>setDraft({...draft,body:event.target.value})}/></label><div className="outreach-send-actions"><a href={gmailComposeUrl(draft)} target="_blank" rel="noopener noreferrer"><ExternalLink/>Open in Gmail</a><button type="button" onClick={async()=>{await navigator.clipboard.writeText(copyableEmail(draft));setNotice('Subject and body copied.');}}><Copy/>Copy Email</button><button type="button" onClick={()=>void markSent()}><Save/>Mark as Sent</button></div><p>Opening Gmail does not mark this lead as contacted. Use “Mark as Sent” only after you send it.</p></div>}
    </section>
   </>}</section>
  </div>
 </main>;
}
