'use client';
import {useState,type FormEvent} from 'react';
import {catalogText} from '@/lib/catalog-i18n';
import {type Locale,type Product} from '@/lib/products';
export function QuoteForm({locale,products,selectedProduct,selectedColorway}:{locale:Locale;products:Product[];selectedProduct?:Product;selectedColorway?:string}) {
 const t=catalogText[locale];const [productId,setProductId]=useState(selectedProduct?.id??'');const [colorCode,setColorCode]=useState(selectedColorway??'');const [ready,setReady]=useState('');const [error,setError]=useState('');
 const p=selectedProduct??products.find(p=>p.id===productId);const c=p?.colorways.find(c=>c.code===(selectedColorway??colorCode))??p?.colorways.find(c=>c.code===p.heroColorwayCode);
 function submit(e:FormEvent<HTMLFormElement>) {e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const v=(key:string)=>String(f.get(key)??'').trim();
 if(!p||!c||!form.checkValidity()||['name','company','country'].some(k=>v(k).length<2)||v('phone').replace(/\D/g,'').length<7||!Number.isFinite(Number(v('quantity')))||Number(v('quantity'))<=0){setError(t.required);form.reportValidity();return;}
 const message=['BIN MANSOOR CARPET',t.quote,`${t.name}: ${v('name')}`,`${t.company}: ${v('company')}`,`${t.country}: ${v('country')}`,`${t.phone}: ${v('phone')}`,v('email')?`${t.email}: ${v('email')}`:'',`${t.product}: ${p.name[locale]}`,`${t.code}: ${p.binMansoorCode}`,`${t.factoryRef}: ${p.originalCode}`,`${t.selected}: ${c.name[locale]} — ${c.code}`,`${t.quantity}: ${v('quantity')} m²`,v('message')?`${t.message}: ${v('message')}`:''].filter(Boolean).join('\n');
 const url='https://wa.me/905303513037?text='+encodeURIComponent(message);setReady(url);setError('');window.open(url,'_blank','noopener,noreferrer');}
 const input=(name:string,label:string,type='text',optional=false)=><label>{label}<input name={name} type={type} required={!optional} minLength={type==='text'?2:undefined} min={type==='number'?'0.01':undefined} step={type==='number'?'any':undefined} maxLength={type==='number'?undefined:200} autoComplete={name==='name'?'name':name==='company'?'organization':name==='country'?'country-name':name==='phone'?'tel':name==='email'?'email':'off'} dir={type==='tel'||type==='email'?'ltr':undefined}/></label>;
 return <form className="quote-form" onSubmit={submit} onChange={()=>{setReady('');setError('');}}><p className="text-sm text-black/65 sm:col-span-2">{t.moq}</p>{input('name',t.name)}{input('company',t.company)}{input('country',t.country)}{input('phone',t.phone,'tel')}{input('email',t.email,'email',true)}{input('quantity',t.quantity,'number')}
 {selectedProduct?<label>{t.product}<input readOnly value={p?.name[locale]??''}/></label>:<label>{t.product}<select required value={productId} onChange={e=>{setProductId(e.target.value);setColorCode('');}}><option value="">{t.select}</option>{products.map(p=><option key={p.id} value={p.id}>{p.name[locale]} — {p.binMansoorCode}</option>)}</select></label>}
 <label>{t.code}<input readOnly value={p?.binMansoorCode??''} dir="ltr"/></label>
 {selectedColorway?<label className="sm:col-span-2">{t.selected}<input readOnly value={c?`${c.name[locale]} — ${c.code}`:''}/></label>:<label className="sm:col-span-2">{t.selected}<select required disabled={!p} value={c?.code??''} onChange={e=>setColorCode(e.target.value)}>{!p&&<option value="">{t.select}</option>}{p?.colorways.map(c=><option key={c.code} value={c.code}>{c.name[locale]} — {c.code}</option>)}</select></label>}
 <label className="sm:col-span-2">{t.message}<textarea name="message" rows={4} maxLength={2500}/></label><p className="sm:col-span-2 text-sm leading-6 text-black/60">{t.handoff}</p>{error&&<p role="alert" className="sm:col-span-2 text-red-800">{error}</p>}<button className="btn-primary sm:col-span-2" type="submit">{t.send}</button>{ready&&<div role="status" className="sm:col-span-2"><p>{t.sent}</p><a href={ready} target="_blank" rel="noreferrer" className="underline">{t.open}</a></div>}</form>;
}
