import {notFound} from 'next/navigation';
import {ProductGallery} from '@/components/product-gallery';
import {getDictionary,isLocale,locales} from '@/lib/i18n';
import {getProduct,products,productAliases,type Locale,type TechnicalSpecs} from '@/lib/products';
import {catalogText} from '@/lib/catalog-i18n';
import {pageMetadata,siteUrl} from '@/lib/seo';
import {CopyCode} from '@/components/copy-code';
import {ProductCard} from '@/components/product-card';
export function generateStaticParams(){return locales.flatMap(locale=>[...products.map(p=>p.slug),...Object.keys(productAliases)].map(slug=>({locale,slug})));}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const p=getProduct(slug);return p&&isLocale(locale)?pageMetadata(locale,`/products/${p.slug}`,`${p.name[locale]} ${p.binMansoorCode}`,p.description[locale],p.heroImage):{};}
const specLabels:Record<keyof TechnicalSpecs,Record<Locale,string>>={material:{ar:'الخامة',tr:'Malzeme',en:'Material'},construction:{ar:'طريقة التصنيع',tr:'Üretim tekniği',en:'Construction'},pileHeight:{ar:'ارتفاع الوبر',tr:'Hav yüksekliği',en:'Pile height'},pileWeight:{ar:'وزن الوبر',tr:'Hav ağırlığı',en:'Pile weight'},totalWeight:{ar:'الوزن الكلي',tr:'Toplam ağırlık',en:'Total weight'},density:{ar:'الكثافة',tr:'Yoğunluk',en:'Density'},backing:{ar:'الظهر',tr:'Taban',en:'Backing'},availableSizes:{ar:'المقاسات',tr:'Ölçüler',en:'Sizes'},sizes:{ar:'المقاسات',tr:'Ölçüler',en:'Sizes'},width:{ar:'العرض',tr:'En',en:'Width'},customColors:{ar:'ألوان حسب الطلب',tr:'Özel renkler',en:'Custom colours'},customDesign:{ar:'تصميم حسب الطلب',tr:'Özel tasarım',en:'Custom design'},application:{ar:'الاستخدام',tr:'Kullanım alanı',en:'Application'},leadTime:{ar:'مدة التجهيز',tr:'Teslim süresi',en:'Lead time'}};
export default async function ProductPage({params}:{params:Promise<{locale:string;slug:string}>}) {
 const {locale,slug}=await params;if(!isLocale(locale))notFound();const p=getProduct(slug);if(!p)notFound();const t=catalogText[locale];const d=getDictionary(locale);const specs=Object.entries(p.technicalSpecs).filter(([,v])=>v!==null&&v!==''&&(!Array.isArray(v)||v.length>0));
 const related=products.filter(item=>item.id!==p.id).map(item=>({item,score:(item.collection.en===p.collection.en?100:0)+(item.styles.some(style=>p.styles.some(current=>current.en===style.en))?10:0)+(item.categoryKey===p.categoryKey?1:0)})).sort((a,b)=>b.score-a.score||a.item.sortOrder-b.item.sortOrder).slice(0,4).map(value=>value.item);
 const breadcrumbItems=[{name:d.nav.products,url:`${siteUrl}/${locale}/products`},{name:p.category[locale],url:`${siteUrl}/${locale}/products?category=${p.categoryKey}`},{name:p.collection[locale],url:`${siteUrl}/${locale}/products?collection=${encodeURIComponent(p.collection.en)}`},{name:p.name[locale],url:`${siteUrl}/${locale}/products/${p.slug}`}];
 return <main id="main-content" className="product-detail site-shell py-10 sm:py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:breadcrumbItems.map((item,index)=>({'@type':'ListItem',position:index+1,name:item.name,item:item.url}))})}}/><nav aria-label={locale==='ar'?'مسار الصفحة':locale==='tr'?'Sayfa yolu':'Breadcrumb'} className="mb-10 text-sm text-black/60"><ol className="flex flex-wrap items-center gap-2" dir={locale==='ar'?'rtl':'ltr'}><li><a className="underline" href={`/${locale}/products`}>{d.nav.products}</a></li><li aria-hidden="true">›</li><li><a className="underline" href={`/${locale}/products?category=${p.categoryKey}`}>{p.category[locale]}</a></li><li aria-hidden="true">›</li><li><a className="underline" href={`/${locale}/products?collection=${encodeURIComponent(p.collection.en)}`}>{p.collection[locale]}</a></li><li aria-hidden="true">›</li><li aria-current="page">{p.name[locale]}</li></ol></nav><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:gap-16"><ProductGallery product={p} locale={locale}/><div className="min-w-0 lg:sticky lg:top-28 lg:self-start"><p className="eyebrow mb-7">{p.category[locale]}</p><h1 className="display-title">{p.name[locale]}</h1><div className="mt-7 flex flex-wrap items-center gap-4"><p dir="ltr" className="font-mono text-xl">{p.binMansoorCode}</p><CopyCode code={p.binMansoorCode} locale={locale}/></div><p className="mt-5 text-lg leading-8 text-black/65">{p.description[locale]}</p><dl className="product-specs mt-8"><div><dt>{t.factoryRef}</dt><dd><bdi>{p.originalCode}</bdi></dd></div><div><dt>{t.collection}</dt><dd>{p.collection[locale]}</dd></div><div><dt>{t.style}</dt><dd>{p.styles.map(s=>s[locale]).join(' / ')}</dd></div></dl>{p.availability.minimumOrderQuantity!==null&&<p className="mt-8 border-s-2 border-[#a4875a] ps-5">{t.moq}</p>}{specs.length>0&&<section className="mt-10"><h2 className="text-2xl">{t.specs}</h2><dl className="product-specs">{specs.map(([key,value])=><div key={key}><dt>{specLabels[key as keyof TechnicalSpecs][locale]}</dt><dd>{Array.isArray(value)?value.join(', '):typeof value==='object'?value?.[locale]:typeof value==='boolean'?value?t.yes:t.no:value}</dd></div>)}</dl></section>}{p.documents.catalogPdf&&<a className="btn-secondary mt-6" href={p.documents.catalogPdf}>{t.catalogPdf}</a>}{p.documents.technicalSheetPdf&&<a className="btn-secondary mt-6" href={p.documents.technicalSheetPdf}>{t.technicalPdf}</a>}</div></div><section className="mt-24 border-t border-black/10 pt-16"><h2 className="text-3xl sm:text-4xl">{t.related}</h2><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{related.map(item=><ProductCard key={item.id} product={item} locale={locale} viewLabel={d.common.view}/>)}</div></section></main>;
}
